#### 导入相关包

In [1]:
import numpy as np
import pandas as pd
import os

#### 读取数据与修改列名

In [2]:
IPF_GWAS = pd.read_csv(r"C:\Users\acer\Desktop\课题资料\TWAS_IPF课题\数据处理\IPF-GWAS.txt",encoding = "utf-8",sep=' ')

In [4]:
IPF_GWAS = IPF_GWAS.rename(columns={"p":"P","chromosome":"Chr"})
IPF_GWAS

,rsid,Chr,position,non_effect_allele,effect_allele,effect_allele_frequency,studies_included,imputation_quality_by_study,effect_direction_by_study,beta,standard_error,P
0,rs12238997,1,693731.0,A,G,0.120628,Y:Y:N,0.740:0.555:NA,+:+:NA,0.080366,0.077610,0.300431
1,rs4951859,1,729679.0,C,G,0.849634,Y:Y:N,0.864:0.514:NA,-:-:NA,-0.097225,0.073169,0.183921
2,rs58276399,1,731718.0,T,C,0.125864,Y:Y:N,0.858:0.668:NA,+:+:NA,0.052040,0.076594,0.496869
3,rs141242758,1,734349.0,T,C,0.125963,Y:Y:N,0.872:0.679:NA,+:+:NA,0.051265,0.076582,0.503228
4,rs3094315,1,752566.0,G,A,0.846473,Y:Y:N,0.994:0.667:NA,-:-:NA,-0.095081,0.072816,0.191629
...,...,...,...,...,...,...,...,...,...,...,...,...
10790929,22:51220088,22,51220088.0,G,A,0.002967,Y:N:Y,0.609:NA:0.630,+:NA:+,0.122390,0.329653,0.710436
10790930,rs115055839,22,51221731.0,T,C,0.064845,Y:N:Y,0.824:NA:0.522,-:NA:-,-0.113185,0.073769,0.124953
10790931,rs114553188,22,51222100.0,G,T,0.054357,Y:Y:Y,0.747:0.672:0.747,-:+:+,0.079733,0.073870,0.280425
10790932,rs6010090,22,51223637.0,G,A,0.054224,Y:Y:Y,0.741:0.667:0.740,-:+:+,0.082218,0.073926,0.266067
10790933,rs9616985,22,51229805.0,T,C,0.064459,Y:N:Y,0.802:NA:0.508,-:NA:-,-0.119156,0.073981,0.107263

In [5]:
neutrophil_3895 = pd.read_csv(r"C:\Users\acer\Desktop\neutrophil_3895",encoding = "utf-8",sep='\t')

In [7]:
neutrophil_3895 = neutrophil_3895.rename(columns={"ID_dbSNP49":"rsid","CHR":"Chr"})
neutrophil_3895

,VARIANT,rsid,Chr,BP,REF,ALT,ALT_MINOR,DIRECTION,EFFECT,SE,P,MLOG10P,ALT_FREQ,MA_FREQ
0,1:10177_A_AC,rs367896724,1,10177,A,AC,True,-,-0.005526,0.004943,0.2636,0.579059,0.3924,0.3924
1,1:10352_T_TA,rs555500075,1,10352,T,TA,True,-,-0.005651,0.005081,0.2661,0.574918,0.3855,0.3855
2,1:10616_CCGCCGTTGCAAAGGCGCGCCG_C,rs376342519,1,10616,CCGCCGTTGCAAAGGCGCGCCG,C,False,-,-0.024385,0.032519,0.4533,0.343573,0.9942,0.0058
3,1:11008_C_G,rs575272151,1,11008,C,G,True,-,-0.002211,0.008557,0.7961,0.099042,0.0851,0.0851
4,1:11012_C_G,rs544419019,1,11012,C,G,True,-,-0.006360,0.008611,0.4601,0.337142,0.0844,0.0844
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29538401,22:51239586_T_G,rs535432390,22,51239586,T,G,True,+,0.046777,0.050956,0.3586,0.445362,0.0018,0.0018
29538402,22:51239652_G_T,rs564418969,22,51239652,G,T,True,-,-0.028715,0.099902,0.7738,0.111380,0.0008,0.0008
29538403,22:51239794_C_A,rs561893765,22,51239794,C,A,True,-,-0.035079,0.051019,0.4917,0.308284,0.0020,0.0020
29538404,22:51240820_C_T,rs5770837,22,51240820,C,T,True,+,0.003463,0.013411,0.7963,0.098948,0.0264,0.0264
29538405,22:51244237_C_T,rs575160859,22,51244237,C,T,True,-,-0.016765,0.020780,0.4198,0.376982,0.0123,0.0123

In [8]:
nosmoke_3654 = pd.read_csv(r"C:\Users\acer\Desktop\nosmoke_3654.txt",encoding = "utf-8",sep='\t')

In [10]:
nosmoke_3654 = nosmoke_3654.rename(columns={"SNPID_UKB":"rsid","CHR":"Chr"})
nosmoke_3654

,SNP,Chr,BP,A1,TEST,NMISS,OR,SE,L95,U95,STAT,P,A2,MAF,NCHROBS,rsid,A1_UKB,A2_UKB,INFO_UKB,MAF_UKB
0,1:715265:C_T,1,715265,T,ADD,379655,1.006,0.013330,0.9803,1.033,0.4646,0.6422,C,0.033160,763522,rs12184267,C,T,0.926915,0.036638
1,1:715367:A_G,1,715367,G,ADD,380041,1.004,0.013290,0.9785,1.031,0.3218,0.7476,A,0.033300,764302,rs12184277,A,G,0.931148,0.036769
2,1:717485:A_C,1,717485,A,ADD,380072,1.005,0.013300,0.9789,1.031,0.3589,0.7197,C,0.033290,764360,rs12184279,C,A,0.925230,0.036463
3,1:720381:G_T,1,720381,T,ADD,380841,1.004,0.013060,0.9786,1.030,0.3005,0.7638,G,0.034550,765908,rs116801199,G,T,0.932145,0.037110
4,1:721290:C_G,1,721290,C,ADD,380663,1.005,0.013100,0.9791,1.031,0.3447,0.7303,G,0.034300,765558,rs12565286,G,C,0.936321,0.037208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10599049,22:51221731:C_T,22,51221731,C,ADD,384765,1.003,0.008971,0.9860,1.021,0.3894,0.6970,T,0.072950,773812,rs115055839,T,C,0.996764,0.073203
10599050,22:51222100:G_T,22,51222100,T,ADD,378412,1.010,0.010840,0.9883,1.031,0.8757,0.3812,G,0.049370,761036,rs114553188,G,T,0.937292,0.056818
10599051,22:51223637:A_G,22,51223637,A,ADD,378205,1.008,0.010880,0.9871,1.030,0.7686,0.4421,G,0.049010,760624,rs6010090,G,A,0.935909,0.055874
10599052,22:51224208:A_G,22,51224208,A,ADD,384964,1.202,0.181900,0.8413,1.716,1.0100,0.3124,G,0.000169,774210,rs116656403,G,A,1.000000,0.001750
10599053,22:51229805:C_T,22,51229805,C,ADD,383940,1.003,0.009023,0.9850,1.020,0.2824,0.7776,T,0.072180,772150,rs9616985,T,C,0.988928,0.073586

In [11]:
smokeout_3239 = pd.read_csv(r"C:\Users\acer\Desktop\smokeout_3239.txt",encoding = "utf-8",sep='\t')

In [13]:
smokeout_3239 = smokeout_3239.rename(columns={"SNPID_UKB":"rsid","CHR":"Chr"})
smokeout_3239

,SNP,Chr,BP,A1,TEST,NMISS,BETA,SE,L95,U95,STAT,P,A2,MAF,NCHROBS,rsid,A1_UKB,A2_UKB,INFO_UKB,MAF_UKB
0,1:715265:C_T,1,715265,T,ADD,323269,-0.007344,0.01681,-0.04029,0.025600,-0.43700,0.6621,C,0.033160,763522,rs12184267,C,T,0.926915,0.036638
1,1:715367:A_G,1,715367,G,ADD,323603,-0.001578,0.01678,-0.03448,0.031320,-0.09401,0.9251,A,0.033300,764302,rs12184277,A,G,0.931148,0.036769
2,1:717485:A_C,1,717485,A,ADD,323620,-0.003818,0.01679,-0.03674,0.029100,-0.22740,0.8201,C,0.033290,764360,rs12184279,C,A,0.925230,0.036463
3,1:720381:G_T,1,720381,T,ADD,324274,-0.008445,0.01646,-0.04071,0.023820,-0.51300,0.6079,G,0.034550,765908,rs116801199,G,T,0.932145,0.037110
4,1:721290:C_G,1,721290,C,ADD,324122,-0.006432,0.01653,-0.03883,0.025960,-0.38920,0.6972,G,0.034300,765558,rs12565286,G,C,0.936321,0.037208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10440059,22:51221731:C_T,22,51221731,C,ADD,327636,0.007482,0.01131,-0.01468,0.029650,0.66160,0.5082,T,0.072950,773812,rs115055839,T,C,0.996764,0.073203
10440060,22:51222100:G_T,22,51222100,T,ADD,322208,-0.017490,0.01367,-0.04428,0.009308,-1.27900,0.2009,G,0.049370,761036,rs114553188,G,T,0.937292,0.056818
10440061,22:51223637:A_G,22,51223637,A,ADD,322046,-0.017510,0.01373,-0.04441,0.009403,-1.27500,0.2023,G,0.049010,760624,rs6010090,G,A,0.935909,0.055874
10440062,22:51224208:A_G,22,51224208,A,ADD,327794,-0.169700,0.22660,-0.61390,0.274400,-0.74900,0.4538,G,0.000169,774210,rs116656403,G,A,1.000000,0.001750
10440063,22:51229805:C_T,22,51229805,C,ADD,326920,0.008694,0.01137,-0.01358,0.030970,0.76500,0.4443,T,0.072180,772150,rs9616985,T,C,0.988928,0.073586

In [14]:
neutrophil_3859 = pd.read_csv(r"C:\Users\acer\Desktop\neutrophil_3859",encoding = "utf-8",sep='\t')

In [16]:
neutrophil_3859 = neutrophil_3859.rename(columns={"SNP":"rsid","CHR":"Chr"})
neutrophil_3859

,rsid,Chr,POS,A1,A2,A1/A2,EAF,Beta,se,P,N,INFO
0,rs367896724,1,10177,AC,A,A,0.399890,-0.006843,0.005639,0.224974,131564,0.489705
1,rs555500075,1,10352,TA,T,T,0.388805,-0.003797,0.005857,0.516756,131564,0.460010
2,rs376342519,1,10616,C,CCGCCGTTGCAAAGGCGCGCCG,CCGCCGTTGCAAAGGCGCGCCG,0.995323,-0.055187,0.040297,0.170843,131564,0.502016
3,rs575272151,1,11008,G,C,C,0.085470,-0.005830,0.009748,0.549779,131564,0.510645
4,rs544419019,1,11012,G,C,C,0.085470,-0.005830,0.009748,0.549779,131564,0.510645
...,...,...,...,...,...,...,...,...,...,...,...,...
29538401,rs535432390,22,51239586,G,T,T,0.001799,0.049353,0.059582,0.407493,131564,0.578408
29538402,rs564418969,22,51239652,T,G,G,0.000229,-0.257877,0.195190,0.186447,131564,0.440537
29538403,rs561893765,22,51239794,A,C,C,0.001607,-0.022733,0.066321,0.731776,131564,0.583468
29538404,rs5770837,22,51240820,T,C,C,0.025118,0.004043,0.015982,0.800282,131564,0.614343
29538405,rs575160859,22,51244237,T,C,C,0.013128,-0.017355,0.024134,0.472068,131564,0.493825

In [17]:
Meta_SLE = pd.read_csv(r"C:\Users\acer\Desktop\MetaSLE.txt",encoding = "utf-8",sep='\t')

In [19]:
Meta_SLE = Meta_SLE.rename(columns={"P-value":"P","SNP":"rsid","CHR":"Chr"})
Meta_SLE

         Chr         rsid        BP A1lele1 Allele2  Zscore       P
0          1   rs12562034    768448       a       g  -0.915  0.3604
1          1    rs7518545    769963       a       g  -0.904  0.3660
2          1   rs12124819    776546       a       g  -0.075  0.9405
3          1  rs117086422    845635       t       c  -0.777  0.4374
4          1   rs28612348    846078       t       c  -0.826  0.4090
...      ...          ...       ...     ...     ...     ...     ...
8929420   22  rs150488734  51167604       t       c   0.843  0.3991
8929421   22     rs756638  51171693       a       g   0.244  0.8076
8929422   22  rs190935456  51172439       a       g   1.242  0.2141
8929423   22    rs3810648  51175626       a       g   0.018  0.9853
8929424   22    rs2285395  51178090       a       g  -0.786  0.4317

[8929425 rows x 7 columns]

#### 筛选P值小于5e-8，并输出

In [44]:
l = ["neutrophil_3895","nosmoke_3654","smokeout_3239","neutrophil_3859","MetaSLE","SpainSLE"]
for i in l:
    print(i)
    l = eval(i)
    a = l[l["P"] < 5e-8]
    print(len(a))
    a.to_csv(r"C:\Users\acer\Desktop\%s.csv"%(i),sep=',',encoding = "utf-8")

neutrophil_3895
34094
nosmoke_3654
5368
smokeout_3239
705
neutrophil_3859
25937
MetaSLE
15812
SpainSLE
1586

#### 读入独立的snp

In [20]:
neutrophil3895 = pd.read_csv(r"C:\Users\acer\Desktop\neutrophil3895",encoding = "utf-8")

In [21]:
nosmoke3654 = pd.read_csv(r"C:\Users\acer\Desktop\nosmoke3654",encoding = "utf-8")

In [22]:
smokeout3239 = pd.read_csv(r"C:\Users\acer\Desktop\smokeout3239.csv",encoding = "utf-8")

In [30]:
# 修改列名
smokeout3239 = smokeout3239.rename(columns={"rsID":"rsid","CHR":"Chr"})
smokeout3239

     Chr       POS         rsid             P
0      1  43635814   rs59745912  2.140000e-10
1      1  57654041     rs155302  2.970000e-09
2      1  62712535  rs181246591  8.240000e-10
3      1  66833350  rs373919185  9.880000e-10
4      1  75529659  rs746340203  2.920000e-08
..   ...       ...          ...           ...
238   21  38637204  rs117103828  6.100000e-10
239   21  45269102   rs11911457  2.990000e-08
240   22  27878103  rs777030150  7.900000e-09
241   22  28286535  rs532337262  2.450000e-10
242   22  32272075  rs747231551  3.700000e-12

[243 rows x 4 columns]

In [23]:
neutrophil3859 = pd.read_csv(r"C:\Users\acer\Desktop\neutrophil3859",encoding = "utf-8")

In [24]:
MetaSLE = pd.read_csv(r"C:\Users\acer\Desktop\Meta-SLE",encoding = "utf-8")

#### 第一步合并   补全原始数据

In [34]:
neutrophil__3895 = pd.merge(neutrophil_3895,neutrophil3895,how='inner',on=["rsid"])
neutrophil__3895

,VARIANT,rsid,Chr,BP,REF,ALT,ALT_MINOR,DIRECTION,EFFECT,SE,P_x,MLOG10P,ALT_FREQ,MA_FREQ,Unnamed: 0,P_y
0,1:8913656_A_G,rs12752838,1,8913656,A,G,False,+,0.023618,0.003580,4.189000e-11,10.377850,0.5035,0.4965,46,4.189000e-11
1,1:28186506_A_C,rs56232812,1,28186506,A,C,True,-,-0.033565,0.005939,1.592000e-08,7.798090,0.1038,0.1038,57,1.592000e-08
2,1:36943916_C_G,rs3917932,1,36943916,C,G,False,-,-0.047669,0.003629,2.062000e-39,38.685790,0.5758,0.4242,130,2.062000e-39
3,1:42235796_C_T,rs2137364,1,42235796,C,T,True,-,-0.020858,0.003717,2.010000e-08,7.696821,0.3669,0.3669,185,2.010000e-08
4,1:46446096_A_G,rs72692639,1,46446096,A,G,True,+,0.024339,0.004075,2.331000e-09,8.632434,0.2592,0.2592,400,2.331000e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,19:51879994_G_A,rs34733715,19,51879994,G,A,True,-,-0.023747,0.004095,6.695000e-09,8.174224,0.2624,0.2624,34044,6.695000e-09
180,20:62308159_A_G,rs62207043,20,62308159,A,G,False,+,0.020407,0.003713,3.871000e-08,7.412206,0.5691,0.4309,34050,3.871000e-08
181,21:40463283_G_A,rs9977672,21,40463283,G,A,True,-,-0.025539,0.004146,7.287000e-10,9.137464,0.2583,0.2583,34051,7.287000e-10
182,22:18171650_C_T,rs5013026,22,18171650,C,T,False,+,0.020625,0.003579,8.295000e-09,8.081169,0.5045,0.4955,34085,8.295000e-09
183,22:31813058_A_T,rs35955747,22,31813058,A,T,False,+,0.020749,0.003594,7.793000e-09,8.108304,0.5393,0.4607,34094,7.793000e-09

In [35]:
nosmoke__3654 = pd.merge(nosmoke_3654,nosmoke3654,how='inner',on=["rsid"])
nosmoke__3654

,SNP,Chr,BP,A1,TEST,NMISS,OR,SE,L95,U95,...,A2,MAF,NCHROBS,rsid,A1_UKB,A2_UKB,INFO_UKB,MAF_UKB,Unnamed: 0,P_y
0,1:33834455:A_G,1,33834455,A,ADD,383438,1.0280,0.004937,1.0180,1.0380,...,G,0.3373,771142,rs4653111,A,G,0.996873,0.332188,2,2.985000e-08
1,1:44083015:A_G,1,44083015,G,ADD,384793,0.9687,0.004969,0.9593,0.9781,...,A,0.3251,773868,rs653953,G,A,0.999498,0.329681,71,1.480000e-10
2,1:50603995:A_C,1,50603995,C,ADD,383770,0.9690,0.005740,0.9581,0.9800,...,A,0.2083,771804,rs12022778,A,C,0.993892,0.212668,161,4.056000e-08
3,1:66407352:A_G,1,66407352,A,ADD,380897,1.0260,0.004733,1.0170,1.0360,...,G,0.4343,766038,rs7528604,G,A,0.994011,0.436062,162,4.926000e-08
4,1:73647800:A_C,1,73647800,A,ADD,378017,0.9739,0.004722,0.9649,0.9829,...,C,0.4561,760208,rs12133935,C,A,0.991779,0.445909,163,2.066000e-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,16:69974546:A_G,16,69974546,G,ADD,383592,0.9670,0.004878,0.9578,0.9762,...,A,0.3507,771452,rs3748387,A,G,0.997736,0.361517,5306,5.619000e-12
70,17:1995177:C_T,17,1995177,C,ADD,378706,1.0310,0.004706,1.0220,1.0410,...,T,0.4699,761632,rs4790874,C,T,0.989037,0.468449,5336,7.223000e-11
71,18:53707569:C_G,18,53707569,C,ADD,375839,1.0420,0.007586,1.0270,1.0580,...,G,0.1090,755870,rs140125866,G,C,0.967063,0.109209,5359,4.959000e-08
72,20:19649757:A_G,20,19649757,G,ADD,382365,1.0280,0.004945,1.0180,1.0380,...,A,0.3384,768972,rs2424246,A,G,0.995547,0.344738,5366,2.219000e-08
73,20:31163573:G_T,20,31163573,T,ADD,381793,0.9703,0.005504,0.9599,0.9808,...,G,0.2362,767830,rs10875486,G,T,0.993719,0.240988,5368,4.230000e-08

In [36]:
smokeout__3239 = pd.merge(smokeout_3239,smokeout3239,how='inner',on=["rsid"])
smokeout__3239

,SNP,Chr_x,BP,A1,TEST,NMISS,BETA,SE,L95,U95,...,MAF,NCHROBS,rsid,A1_UKB,A2_UKB,INFO_UKB,MAF_UKB,Chr_y,POS,P_y
0,1:43635814:C_T,1,43635814,T,ADD,327781,1.4520,0.2287,1.0040,1.901,...,0.000174,774182,rs59745912,C,T,0.995100,0.003488,1,43635814,2.140000e-10
1,1:57654041:A_T,1,57654041,T,ADD,327729,1.2050,0.2031,0.8069,1.603,...,0.000216,774050,rs155302,A,T,0.900718,0.002191,1,57654041,2.970000e-09
2,1:62712535:C_T,1,62712535,T,ADD,327762,1.0050,0.1636,0.6841,1.326,...,0.000316,774136,rs181246591,C,T,0.958510,0.000321,1,62712535,8.240000e-10
3,1:66833350:G_T,1,66833350,G,ADD,327689,1.0700,0.1751,0.7268,1.413,...,0.000271,773952,rs373919185,T,G,0.905012,0.000326,1,66833350,9.880000e-10
4,1:75529659:C_G,1,75529659,C,ADD,327740,1.2240,0.2207,0.7915,1.657,...,0.000174,774082,rs746340203,G,C,0.921853,0.000220,1,75529659,2.920000e-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,21:38637204:A_G,21,38637204,A,ADD,327736,0.9087,0.1468,0.6209,1.197,...,0.000400,774084,rs117103828,G,A,0.947518,0.000431,21,38637204,6.100000e-10
239,21:45269102:A_G,21,45269102,A,ADD,327751,1.0900,0.1967,0.7047,1.476,...,0.000229,774100,rs11911457,G,A,0.905102,0.001675,21,45269102,2.990000e-08
240,22:27878103:C_T,22,27878103,C,ADD,327746,1.1350,0.1967,0.7496,1.521,...,0.000227,774086,rs777030150,T,C,0.912570,0.000263,22,27878103,7.900000e-09
241,22:28286535:A_G,22,28286535,A,ADD,327668,1.1250,0.1777,0.7765,1.473,...,0.000275,773918,rs532337262,G,A,0.904449,0.000389,22,28286535,2.450000e-10
242,22:32272075:C_T,22,32272075,T,ADD,327660,1.3100,0.1885,0.9403,1.679,...,0.000243,773894,rs747231551,C,T,0.908802,0.000373,22,32272075,3.700000e-12

In [37]:
neutrophil__3859 = pd.merge(neutrophil_3859,neutrophil3859,how='inner',on=["rsid"])
neutrophil__3859

,rsid,Chr,POS,A1,A2,A1/A2,EAF,Beta,se,P,N,INFO,Unnamed: 0,P.value
0,rs12752838,1,8913656,G,A,A,0.505109,0.022846,0.003873,3.659251e-09,131564,0.993541,6,3.659251e-09
1,rs56232812,1,28186506,C,A,A,0.103782,-0.036794,0.006412,9.574352e-09,131564,0.971664,13,9.574352e-09
2,rs3917932,1,36943916,G,C,C,0.575930,-0.047337,0.003934,2.383349e-33,131564,0.990364,91,2.383349e-33
3,rs785515,1,46562662,C,A,A,0.437986,-0.024262,0.003909,5.420253e-10,131564,0.989663,295,5.420253e-10
4,rs12136896,1,56617956,A,G,G,0.356801,0.023416,0.004037,6.612847e-09,131564,0.996292,347,6.612847e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,rs4808798,19,18517506,C,G,G,0.467215,0.025735,0.003888,3.599626e-11,131564,0.994474,25801,3.599626e-11
139,rs4760,19,44153100,G,A,A,0.156224,-0.077139,0.005323,1.347814e-47,131564,1.000000,25832,1.347814e-47
140,rs7255933,19,45766729,A,G,G,0.257206,-0.044139,0.004435,2.454150e-23,131564,1.000000,25870,2.454150e-23
141,rs55720021,19,49144241,T,G,G,0.762935,0.029278,0.004586,1.717918e-10,131564,0.978702,25916,1.717918e-10
142,rs2836884,21,40467643,C,T,T,0.276719,-0.026954,0.004365,6.633686e-10,131564,0.983355,25936,6.633686e-10

In [38]:
Meta__SLE = pd.merge(Meta_SLE,MetaSLE,how='inner',on=["rsid"])
Meta__SLE

,Chr,rsid,BP,A1lele1,Allele2,Zscore,P_x,Unnamed: 0,P_y
0,1,rs4661543,15229101,t,g,5.881,4.072000e-09,1,4.072000e-09
1,1,rs2476601,114377568,a,g,-7.916,2.445000e-15,6,2.445000e-15
2,1,rs6671847,161478810,a,g,-7.913,2.520000e-15,19,2.520000e-15
3,1,rs10912578,173251856,a,g,-8.177,2.910000e-16,69,2.910000e-16
4,1,rs4916215,173314540,t,c,-6.998,2.591000e-12,85,2.591000e-12
5,1,rs946173,183260659,a,g,6.711,1.934000e-11,190,1.934000e-11
6,1,rs12146097,183329261,t,c,-9.166,4.886000e-20,215,4.886000e-20
7,1,rs1174683,183650428,a,g,-5.701,1.188000e-08,298,1.188000e-08
8,2,rs268124,65654364,t,c,-5.684,1.316000e-08,303,1.316000e-08
9,2,rs13019891,113829869,t,g,17.617,1.814000e-69,304,1.814000e-69
10,2,rs512681,119450163,a,c,6.350,2.152000e-10,305,2.152000e-10
11,2,rs7575908,135072001,a,g,-5.939,2.860000e-09,319,2.860000e-09
12,2,rs1990760,163124051,t,c,-5.697,1.219000e-08,321,1.219000e-08
13,2,rs4274624,191958656,t,c,18.145,1.402000e-73,534,1.402000e-73
14,2,rs10048743,213890232,t,g,6.067,1.303000e-09,566,1.303000e-09
15,2,rs2573219,233288667,a,c,12.755,2.912000e-37,573,2.912000e-37
16,3,rs11130650,58470708,t,c,-5.536,3.092000e-08,579,3.092000e-08
17,3,rs9852014,129084581,a,g,11.506,1.232000e-30,580,1.232000e-30
18,3,rs1464446,146601295,t,g,6.462,1.034000e-10,581,1.034000e-10
19,3,rs2936303,159730954,a,g,5.958,2.551000e-09,600,2.551000e-09
20,4,rs11097757,102770948,a,g,7.065,1.611000e-12,728,1.611000e-12
21,5,rs13170409,15764650,a,c,5.617,1.939000e-08,777,1.939000e-08
22,5,rs55849330,100184647,a,c,-5.454,4.933000e-08,778,4.933000e-08
23,5,rs73790123,133425768,t,g,6.802,1.035000e-11,791,1.035000e-11
24,5,rs6889239,150457771,t,c,9.350,8.740000e-21,839,8.740000e-21
25,5,rs2431697,159879978,t,c,-8.026,1.007000e-15,849,1.007000e-15
26,6,rs9368503,27303745,a,t,6.314,2.714000e-10,1503,2.714000e-10
27,6,rs151003642,30960807,c,g,-6.156,7.472000e-10,4692,7.472000e-10
28,6,rs9267393,31469365,a,c,10.433,1.744000e-25,7723,1.744000e-25
29,6,rs112817717,32571565,c,g,7.271,3.580000e-13,10340,3.580000e-13
30,6,rs28383364,32606912,a,g,-10.590,3.325000e-26,11347,3.325000e-26
31,6,rs17843693,32622122,a,g,-14.531,7.693000e-48,11657,7.693000e-48
32,6,rs2854277,32628084,t,c,-22.851,1.420000e-115,11708,1.420000e-115
33,6,rs501480,33563946,t,c,6.103,1.042000e-09,14060,1.042000e-09
34,6,rs115531193,34651311,a,t,-6.032,1.620000e-09,14129,1.620000e-09
35,6,rs4134466,106577368,a,g,-6.955,3.528000e-12,14241,3.528000e-12
36,6,rs675640,138127204,a,c,-5.713,1.108000e-08,14256,1.108000e-08
37,7,rs13238352,128647942,t,c,-15.260,1.416000e-52,14385,1.416000e-52
38,8,rs2736332,11339965,c,g,-9.493,2.242000e-21,14704,2.242000e-21
39,8,rs7823055,55511676,t,g,11.529,9.375000e-31,14758,9.375000e-31
40,10,rs10905367,8472876,c,g,5.479,4.275000e-08,14759,4.275000e-08
41,10,rs7097397,50025396,a,g,6.458,1.064000e-10,14761,1.064000e-10
42,10,rs7899626,63825561,t,c,-5.620,1.909000e-08,14774,1.909000e-08
43,11,rs936472,593453,t,c,-7.053,1.752000e-12,14830,1.752000e-12
44,11,rs353608,35101738,a,g,7.003,2.511000e-12,14960,2.511000e-12
45,11,rs12273982,65535464,a,c,-6.102,1.048000e-09,14981,1.048000e-09
46,11,rs12575600,128324869,c,g,5.494,3.929000e-08,14988,3.929000e-08
47,12,rs10774625,111910219,a,g,-5.584,2.351000e-08,14993,2.351000e-08
48,12,rs35429841,129273505,t,c,-5.777,7.595000e-09,15002,7.595000e-09
49,16,rs7200786,11177801,a,g,-7.180,6.975000e-13,15064,6.975000e-13
50,16,rs1143679,31276811,a,g,-16.298,1.016000e-59,15183,1.016000e-59
51,16,rs13332649,85966683,a,g,-8.794,1.441000e-18,15365,1.441000e-18
52,17,rs3809822,7234112,c,g,5.603,2.104000e-08,15438,2.104000e-08
53,17,rs8074437,38076137,t,g,-5.718,1.081000e-08,15647,1.081000e-08
54,17,rs36023980,73341284,t,c,5.856,4.728000e-09,15676,4.728000e-09
55,19,rs35251378,10459969,a,g,7.459,8.715000e-14,15682,8.715000e-14
56,22,rs3747093,21984379,a,g,-7.469,8.054000e-14,15811,8.054000e-14

#### 第二步合并 匹配暴露于结局

In [41]:
l = ["neutrophil__3895","nosmoke__3654","smokeout__3239","neutrophil__3859","Meta__SLE"]
for i in l:
    c = eval(i)
    Result = pd.merge(c,IPF_GWAS,how='inner',on=["rsid"])
    Result.to_csv(r"C:\Users\acer\Desktop\%s.csv"%(i),sep=',',encoding = "utf-8")

In [42]:
Result = pd.merge(neutrophil__3895,IPF_GWAS,how='inner',on=["rsid"])
Result.to_csv(r"C:\Users\acer\Desktop\s.csv",sep=',',encoding = "utf-8")